name: kaichon
description: A new Flutter application.
version: 1.0.0+6
publish_to: "none"

environment:
  sdk: ">=2.10.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  # blurhash_dart:
  #   git:
  #     url: git://github.com/SHRJamal/blurhash-dart.git
  infinite_scroll_pagination:
    git:
      url: git://github.com/SHRJamal/infinite_scroll_pagination.git
  blurhash_dart: ^1.0.2
  admob_flutter: 1.0.1
  auto_size_text: 2.1.0
  awesome_dialog: 1.3.1
  badges: 1.1.6
  bot_toast: 3.0.5
  cached_network_image: 2.5.0
  # cloud_firestore: 0.16.0+1
  # cloud_functions: 0.9.0
  # connectivity_widget: 0.1.7
  #country_pickers: 1.3.0
  country_pickers: ^2.0.0
  cupertino_icons: 1.0.0 
  day_night_switcher: 0.1.1+1
  deep_pick: 0.6.10
  equatable: 1.2.6
  # fast_i18n: 2.2.0
  # fast_i18n: ^4.1.0
  # fast_i18n: ^4.0.0
  fast_i18n: ^3.0.0
  cloud_functions: ^1.0.4
  cloud_firestore: ^1.0.6
  # firebase_analytics: 7.0.1
  firebase_analytics: ^8.0.1
  # firebase_auth: 0.20.1
  firebase_auth: ^1.1.1
  firebase_auth_web: ^1.0.7
  # firebase_core: 0.7.0
  firebase_core: ^1.0.4
  # firebase_crashlytics: 0.4.0+1
  firebase_crashlytics: ^2.0.1
  # firebase_messaging: 8.0.0-dev.14
  firebase_messaging: ^9.1.2
  # firebase_storage: 7.0.0
  firebase_storage: ^8.0.4
  flappy_search_bar: 1.7.2
  flare_flutter: 2.0.6
  flutter_blurhash: 0.5.0
  flutter_linkify: 4.0.2
  flutter_ringtone_player: 2.0.0
  flutter_sim_country_code: 0.0.3
  flutter_spinkit: 4.1.2+1
  flutter_staggered_grid_view: 0.3.4
  focused_menu: 1.0.2
  font_awesome_flutter: 8.11.0
  # freezed_annotation: 0.12.0
  freezed_annotation: ^0.14.1
  get: 3.25.4
  # google_fonts: 1.1.2
  guard: 1.0.4
  # image: 2.1.19
  image: ^3.0.2
  image_downloader: 0.20.1
  # image_picker: 0.6.7+22
  image_picker: ^0.7.4
  intl: ^0.17.0
  logger: 0.9.4
  meta: any
  modal_bottom_sheet: 1.0.0+1
  # path_provider: 1.6.27
  path_provider: ^2.0.1
  # permission_handler: 5.1.0+2
  permission_handler: ^6.1.3
  photo_view: 0.10.3
  pin_code_fields: 6.1.0
  profanity_filter: 1.0.4
  #pull_to_refresh: 1.6.3
  pull_to_refresh: ^1.6.4
  settings_ui: 0.6.0
  # shared_preferences: 0.5.12+4
  shared_preferences: ^2.0.5
  shimmer: 1.1.2
  # timeago: 2.0.30
  timeago: ^3.0.2
  get_time_ago: ^0.1.6
  #timeago: ^3.0.2
  # url_launcher: 5.7.10
  url_launcher: ^6.0.3

  circular_profile_avatar: ^1.0.8
  # webview_flutter: ^1.0.7
  webview_flutter: ^2.0.4

  agora_rtc_engine: ^1.0.13
  agora_rtm: ^0.9.11
  wakelock: ^0.1.4+1
  random_color: ^1.0.5
  persistent_bottom_nav_bar: ^4.0.2
  convex_bottom_bar: ^3.0.0
  rnd: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # build_runner: 1.10.13
  build_runner: ^2.0.0
  flutter_gen: 3.1.1
  # flutter_launcher_icons: 0.8.1
  flutter_launcher_icons: ^0.9.0
  # freezed: 0.12.7
  # freezed: ^0.14.1+2
  
  # import_sorter: 4.4.1
  import_sorter: ^4.4.3
  lint: 1.3.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/images/icons/
    - assets/images/splash/
    - assets/images/logo-white-bg/
    - assets/images/login-header-bg/
  fonts:
    - family: LucidaGrande
      fonts:
        - asset: assets/fonts/LucidaGrande.ttf
        - asset: assets/fonts/LucidaGrandeBold.ttf
    - family: ZenDots
      fonts:
        - asset: assets/fonts/ZenDots-Regular.ttf
    - family: Brushthai2
      fonts:
        - asset: assets/fonts/SP-Brushthai/SP-Brushthai2.ttf

scripts: derry.yaml

import_sorter:
  comments: false
